=== Varunsingh-21/INFT3101-01/Labs/LAB 2/events.dtd
<!ELEMENT events (organization, event+)>
  <!ELEMENT organization (organizationName, organizationLogo, website?, socialLinks*)>
  <!ELEMENT organizationName (#PCDATA)>
  <!ELEMENT organizationLogo EMPTY>
  <!ATTLIST organizationLogo src CDATA #REQUIRED> 
  <!ELEMENT website (#PCDATA)>
  <!ELEMENT socialLinks (#PCDATA)>
  
  <!ELEMENT event (eventName, Date, hosts, participants, resources, feedback, hashtags* )>
  <!ATTLIST event eventID ID #REQUIRED>

  <!ELEMENT eventName (#PCDATA)>
  <!ELEMENT Date EMPTY>
  <!ATTLIST Date start CDATA #REQUIRED end CDATA #REQUIRED> 

  <!ELEMENT hosts (host+)>
  <!ELEMENT host (hostName,contactInfo)>
  <!ATTLIST host hostID ID #REQUIRED>

  <!ELEMENT hostName (firstName,lastName)>
  <!ELEMENT firstName (#PCDATA)>
  <!ELEMENT lastName (#PCDATA)>

  <!ELEMENT contactInfo (phone,email)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT email (#PCDATA)>

  <!ELEMENT participants (participant+)>
  <!ELEMENT participant (pname,role,contact)>
    <!ELEMENT pname (fName,lName)>
      <!ELEMENT fName (#PCDATA)>
      <!ELEMENT lName (#PCDATA)>

    <!ELEMENT role (attendee,speaker,sponsor)>
    <!ELEMENT attendee (#PCDATA)>   
    <!ELEMENT speaker (#PCDATA)>   
    <!ELEMENT sponsor (#PCDATA)>  
    
    <!ELEMENT contact (pphone,pemail)>
      <!ELEMENT pphone (#PCDATA)>
      <!ELEMENT pemail (#PCDATA)>

  <!ELEMENT resources (venue,equipment*,services?)>
    <!ELEMENT venue (location,capacity)>
      <!ELEMENT location (#PCDATA)>
      <!ELEMENT capacity (#PCDATA)>
    <!ELEMENT equipment (#PCDATA)> 
    <!ELEMENT services (details)> 
      <!ELEMENT details (#PCDATA)>

  <!ELEMENT feedback (comment)>
  <!ATTLIST feedback feedbackID ID #REQUIRED>
  <!ELEMENT comment (#PCDATA)>
  
  <!ELEMENT hashtags (#PCDATA)>

=== Varunsingh-21/INFT3101-01/Labs/LAB 2/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE events SYSTEM "events.dtd">
<events>
<organization>
    <organizationName>StarkInternational</organizationName>
    <organizationLogo src="logo.png"></organizationLogo>
    <website>https://www.marvel.com/</website>
    <socialLinks>https://www.instagram.com/marvel/</socialLinks>
</organization>

<event eventID="EV101">
    <eventName>Thanks Giving</eventName>
    <Date start="28-9-2024" end="30-9-2024"></Date>
    <hosts>
        <host hostID="H101">
            <hostName>
                <firstName>Varun</firstName>
                <lastName>Singh</lastName>
            </hostName>
            <contactInfo>
                <phone>+1 6478964257</phone>
                <email>getfullamrks@gmail.com</email>
            </contactInfo>
        </host>
    </hosts>

    <participants>
        <participant>
            <pname>
                <fName>Drashya</fName>
                <lName>Patel</lName>
            </pname>

            <role>
                <attendee>attendee 1</attendee>
                <speaker>speaker 1</speaker>
                <sponsor>TESLA</sponsor>
            </role>
            <contact>
                <pphone>+1 6372891023</pphone>
                <pemail>yas@gmail.com</pemail>
            </contact>
        </participant>
    </participants>
    <resources>
        <venue>
            <location>CN tower</location>
            <capacity>80</capacity>
        </venue>
        <equipment>Cameras</equipment>
        <services>
            <details>drinks and refreshments</details>
        </services>
    </resources>
    <feedback feedbackID="f101">
        <comment>Great event, Amazing management</comment>
    </feedback>
    <hashtags>#coolparty #weekend #enjoy #thansgiving</hashtags>

</event>


<event eventID="EV102">
    <eventName>Bachlor's Party</eventName>
    <Date start="29-9-2024" end="1-10-2024"></Date>
    <hosts>
        <host hostID="H102">
            <hostName>
                <firstName>Varun</firstName>
                <lastName>Singh</lastName>
            </hostName>
            <contactInfo>
                <phone>+1 6478964257</phone>
                <email>getfullamrks@gmail.com</email>
            </contactInfo>
        </host>
    </hosts>

    <participants>
        <participant>
            <pname>
                <fName>Drashya</fName>
                <lName>Patel</lName>
            </pname>

            <role>
                <attendee>attendee 1</attendee>
                <speaker>speaker 1</speaker>
                <sponsor>TESLA</sponsor>
            </role>
            <contact>
                <pphone>+1 6372891023</pphone>
                <pemail>yas@gmail.com</pemail>
            </contact>
        </participant>
    </participants>
    <resources>
        <venue>
            <location>CN tower</location>
            <capacity>80</capacity>
        </venue>
        <equipment>Cameras</equipment>
        <services>
            <details>drinks and refreshments</details>
        </services>
    </resources>
    <feedback feedbackID="f102">
        <comment>Great event, Amazing management</comment>
    </feedback>
    <hashtags>#coolparty #weekend #enjoy #bachlorparty</hashtags>

</event>



</events>
